### ISSUE TITLE
[Feature]: Log flush output before crash

### ISSUE THREAD

**Issue by pengtianyue025** [cubefs/cubefs#1910]
**Describe the solution you'd like**
- Implement process-level recovery, and flush logs after catch exceptions.

**Additional context**
Considering performance, the service log is output asynchronously by default. When a crash occurs, the last log may not be flushed to the disk in time, making it difficult to locate the problem.

**Comment by NaturalSelect** [comment]
Hello @true1064, this problem still exists?

**Comment by setcy** [comment]
https://github.com/cubefs/cubefs/blob/145d67b955833c73e9c7fbbbba75d4eb89de2332/cmd/cmd.go#L219

It seems that this feature has been implemented.

**Comment by NaturalSelect** [comment]
> https://github.com/cubefs/cubefs/blob/145d67b955833c73e9c7fbbbba75d4eb89de2332/cmd/cmd.go#L219
> 
> It seems that this feature has been implemented.

You are right.

**Comment by true1064** [comment]
> > https://github.com/cubefs/cubefs/blob/145d67b955833c73e9c7fbbbba75d4eb89de2332/cmd/cmd.go#L219
> > 
> > It seems that this feature has been implemented.
> 
> You are right.
this problem still exists:
if child goroutine occurs panic and cause the process exit abnormally，the `defer log.LogFlush() ` will not execute because it's not in a recover() block.
@NaturalSelect @setcy

**Comment by NaturalSelect** [comment]
> > > https://github.com/cubefs/cubefs/blob/145d67b955833c73e9c7fbbbba75d4eb89de2332/cmd/cmd.go#L219
> > > 
> > > It seems that this feature has been implemented.
> > 
> > 
> > You are right.
> > this problem still exists:
> > if child goroutine occurs panic and cause the process exit abnormally，the `defer log.LogFlush() ` will not execute because it's not in a recover() block.
> > @NaturalSelect @setcy

@true1064 I will try to figure out what happended.

**Comment by NaturalSelect** [comment]
It seems that adding defer to each coroutine is the only way to solve the problem.

`runtime.addExitHook` will never work when panic.

**Comment by NaturalSelect** [comment]
@true1064 Inline hook works on this problem. But it looks a little dangerous.

```log
┌──(nature㉿LAPTOP-9TS0FG11)-[~/cubefs]
└─$ ./build/bin/cfs-server -f -c ~/disk/conf/data1.conf 
panic: I'm panic

goroutine 71 [running]:
github.com/cubefs/cubefs/util/errors.hookedPanic({0x16d6a40, 0x1eec3f0})
        util/errors/panichook.go:38 +0x77
main.main.func2()
        cmd/cmd.go:251 +0x3f
created by main.main
        cmd/cmd.go:248 +0xd59

┌──(nature㉿LAPTOP-9TS0FG11)-[~/cubefs]
└─$ cat ~/disk/data1/logs/dataNode/dataNode_error.log 
2023/12/10 00:06:26.961475 [ERROR] cmd.go:250: You should see me in log file
```

**cmd.go:**
```go
func main() {
	flag.Parse()

	Version := proto.DumpVersion("Server")
	if *configVersion {
		fmt.Printf("%v", Version)
		os.Exit(0)
	}

	/*
	 * LoadConfigFile should be checked before start daemon, since it will
	 * call os.Exit() w/o notifying the parent process.
	 */
	cfg, err := config.LoadConfigFile(*configFile)
	if err != nil {
		daemonize.SignalOutcome(err)
		os.Exit(1)
	}

	if !*configForeground {
		if err := startDaemon(); err != nil {
			fmt.Printf("Server start failed: %v\n", err)
			os.Exit(1)
		}
		os.Exit(0)
	}

	/*
	 * We are in daemon from here.
	 * Must notify the parent process through SignalOutcome anyway.
	 */

	role := cfg.GetString(ConfigKeyRole)
	logDir := cfg.GetString(ConfigKeyLogDir)
	logLevel := cfg.GetString(ConfigKeyLogLevel)
	logRotateSize := cfg.GetInt64(ConfigKeyLogRotateSize)
	logRotateHeadRoom := cfg.GetInt64(ConfigKeyLogRotateHeadRoom)
	profPort := cfg.GetString(ConfigKeyProfPort)
	umpDatadir := cfg.GetString(ConfigKeyWarnLogDir)
	buffersTotalLimit := cfg.GetInt64(ConfigKeyBuffersTotalLimit)
	logLeftSpaceLimitStr := cfg.GetString(ConfigKeyLogLeftSpaceLimit)
	logLeftSpaceLimit, err := strconv.ParseInt(logLeftSpaceLimitStr, 10, 64)
	if err != nil || logLeftSpaceLimit == 0 {
		log.LogErrorf("logLeftSpaceLimit is not a legal int value: %v", err.Error())
		logLeftSpaceLimit = log.DefaultLogLeftSpaceLimit
	}
	// Init server instance with specified role configuration.
	var (
		server common.Server
		module string
	)
	switch role {
	case RoleMeta:
		server = metanode.NewServer()
		module = ModuleMeta
	case RoleMaster:
		server = master.NewServer()
		module = ModuleMaster
	case RoleData:
		server = datanode.NewServer()
		module = ModuleData
	case RoleAuth:
		server = authnode.NewServer()
		module = ModuleAuth
	case RoleObject:
		server = objectnode.NewServer()
		module = ModuleObject
	case RoleConsole:
		server = console.NewServer()
		module = ModuleConsole
	case RoleLifeCycle:
		server = lcnode.NewServer()
		module = ModuleLifeCycle
	default:
		err = errors.NewErrorf("Fatal: role mismatch: %s", role)
		fmt.Println(err)
		daemonize.SignalOutcome(err)
		os.Exit(1)
	}

	// Init logging
	var (
		level log.Level
	)
	switch strings.ToLower(logLevel) {
	case "debug":
		level = log.DebugLevel
	case "info":
		level = log.InfoLevel
	case "warn":
		level = log.WarnLevel
	case "error":
		level = log.ErrorLevel
	case "critical":
		level = log.CriticalLevel
	default:
		level = log.ErrorLevel
	}
	rotate := log.NewLogRotate()
	if logRotateSize > 0 {
		rotate.SetRotateSizeMb(logRotateSize)
	}
	if logRotateHeadRoom > 0 {
		rotate.SetHeadRoomMb(logRotateHeadRoom)
	}
	_, err = log.InitLog(logDir, module, level, rotate, logLeftSpaceLimit)
	if err != nil {
		err = errors.NewErrorf("Fatal: failed to init log - %v", err)
		fmt.Println(err)
		daemonize.SignalOutcome(err)
		os.Exit(1)
	}
	defer log.LogFlush()
	errors.AtPanic(func() {
		log.LogFlush()
	})
	go func() {

		log.LogErrorf("You should see me in log file")
		panic("I'm panic")
	}()
	time.Sleep(time.Second * 1)
        ...
}
```
