### ISSUE TITLE
[Bug]: cfs-client 3.3.0 crash

### ISSUE THREAD

**Issue by zcola** [cubefs/cubefs#3049]
### Is there an existing issue for this?

- [X] I have searched all the existing issues

### Priority

low (Default)

### Environment

```markdown
- CubeFS version: 3.3.0
 
2024/01/16 11:19:37 CubeFS Client
Version : v3.3.0
Branch  : HEAD
Commit  : 3d9f15e4cf21e1b7599fed5239d67f4e092f5d4f
Build   : go1.17.13 linux amd64 2023-10-18 07:47
 
```

### Current Behavior

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc pc=0x934089]

goroutine 197838720 [running]:
github.com/cubefs/cubefs/sdk/data/stream.(*ExtentHandler).write(0xc0506d6d20, {0xc056ffe050, 0xc02c361c28, 0x20fb0}, 0x1860000, 0x20000, 0x0)
        sdk/data/stream/extent_handler.go:179 +0x309
github.com/cubefs/cubefs/sdk/data/stream.(*Streamer).doWrite(0xc013a24420, {0xc056ffe050, 0x20000, 0x20fb0}, 0x1860000, 0x20000, 0x1a)
        sdk/data/stream/stream_writer.go:485 +0xa11
github.com/cubefs/cubefs/sdk/data/stream.(*Streamer).write(0xc013a24420, {0xc056ffe050, 0x20000, 0x20fb0}, 0xc045fdaba0, 0xc02745c708, 0x0, 0xc020428228)
        sdk/data/stream/stream_writer.go:335 +0x4b4
github.com/cubefs/cubefs/sdk/data/stream.(*Streamer).handleRequest(0xc02c361f80, {0x9b06a0, 0xc049986480})
        sdk/data/stream/stream_writer.go:260 +0x1a5
github.com/cubefs/cubefs/sdk/data/stream.(*Streamer).server(0xc013a24420)
        sdk/data/stream/stream_writer.go:184 +0x130
created by github.com/cubefs/cubefs/sdk/data/stream.NewStreamer
        sdk/data/stream/stream_reader.go:81 +0x3bb
```

```
2024/01/26 12:45:36.008750 [WARN ] operation.go:610: dcreate: packet(ReqID(135349160)Op(OpMetaCreateDentry)PartitionID(36118)ResultCode(ExistErr)) mp(PartitionID(36118) Start(8388609) End(9223372036854775807) Members([7.34.76.32:17210 7.34.73.161:17210 7.34.72.27:17210]) LeaderAddr(7.34.73.161:17210) Status(2)) req({tmax-dep356-private2 36118 8807910 4613612 c9e6616c1bb469d7a62f93d60a85a36ee402fbfbb439d00076b5ae67 384}) result(ExistErr)
2024/01/26 12:45:57.222108 [ERROR] operation.go:972: iget: packet(ReqID(135350632)Op(OpMetaInodeGet)PartitionID(36118)ResultCode(NotExistErr)) mp(PartitionID(36118) Start(8388609) End(9223372036854775807) Members([7.34.76.32:17210 7.34.73.161:17210 7.34.72.27:17210]) LeaderAddr(7.34.73.161:17210) Status(2)) req({tmax-dep356-private2 36118 8422933}) result(NotExistErr)
2024/01/26 12:45:57.235760 [ERROR] operation.go:972: iget: packet(ReqID(135350641)Op(OpMetaInodeGet)PartitionID(36118)ResultCode(NotExistErr)) mp(PartitionID(36118) Start(8388609) End(9223372036854775807) Members([7.34.76.32:17210 7.34.73.161:17210 7.34.72.27:17210]) LeaderAddr(7.34.73.161:17210) Status(2)) req({tmax-dep356-private2 36118 8422933}) result(NotExistErr)
2024/01/26 12:45:57.235805 [ERROR] inode.go:38: InodeGet: ino(8422933) err(no such file or directory) info(<nil>)
2024/01/26 12:45:57.235812 [ERROR] file.go:143: Attr: ino(8422933) err(no such file or directory)
2024/01/26 13:01:55.079790 [ERROR] extent_client.go:508: Read: stream is not opened yet, ino(8551473) offset(743636992) size(131072)
2024/01/26 13:01:55.079859 [ERROR] super.go:405: Read: ino(8551473) req(Read [ID=0x1144f3a4 Node=0x22f89 Uid=53801 Gid=53801 Pid=1769038] 0xb1 131072 @0x2c530000 dir=false fl=0 lock=0 ffl=OpenReadOnly) err(bad file descriptor) size(0)
2024/01/26 13:01:55.079983 [ERROR] extent_client.go:508: Read: stream is not opened yet, ino(8551473) offset(743702528) size(4096)
2024/01/26 13:01:55.080045 [ERROR] super.go:405: Read: ino(8551473) req(Read [ID=0x1144f3a6 Node=0x22f89 Uid=53801 Gid=53801 Pid=1769038] 0xb1 4096 @0x2c540000 dir=false fl=0 lock=0 ffl=OpenReadOnly) err(bad file descriptor) size(0)
2024/01/26 13:01:55.080216 [ERROR] extent_client.go:508: Read: stream is not opened yet, ino(8551473) offset(743702528) size(4096)
2024/01/26 13:01:55.080259 [ERROR] super.go:405: Read: ino(8551473) req(Read [ID=0x1144f3a8 Node=0x22f89 Uid=53801 Gid=53801 Pid=1769038] 0xb1 4096 @0x2c540000 dir=false fl=0 lock=0 ffl=OpenReadOnly) err(bad file descriptor) size(0)
2024/01/26 13:01:55.351212 [ERROR] extent_client.go:508: Read: stream is not opened yet, ino(8551473) offset(957779968) size(131072)
2024/01/26 13:01:55.351275 [ERROR] super.go:405: Read: ino(8551473) req(Read [ID=0x1145123a Node=0x22f89 Uid=53801 Gid=53801 Pid=1769102] 0x1c 131072 @0x39169000 dir=false fl=0 lock=0 ffl=OpenReadOnly) err(bad file descriptor) size(0)
2024/01/26 13:01:55.351371 [ERROR] extent_client.go:508: Read: stream is not opened yet, ino(8551473) offset(957845504) size(4096)
2024/01/26 13:01:55.351394 [ERROR] super.go:405: Read: ino(8551473) req(Read [ID=0x1145123c Node=0x22f89 Uid=53801 Gid=53801 Pid=1769102] 0x1c 4096 @0x39179000 dir=false fl=0 lock=0 ffl=OpenReadOnly) err(bad file descriptor) size(0)
2024/01/26 13:01:55.351596 [ERROR] extent_client.go:508: Read: stream is not opened yet, ino(8551473) offset(957845504) size(4096)
2024/01/26 13:01:55.351645 [ERROR] super.go:405: Read: ino(8551473) req(Read [ID=0x1145123e Node=0x22f89 Uid=53801 Gid=53801 Pid=1769102] 0x1c 4096 @0x39179000 dir=false fl=0 lock=0 ffl=OpenReadOnly) err(bad file descriptor) size(0)
2024/01/26 13:01:55.398929 [ERROR] extent_client.go:508: Read: stream is not opened yet, ino(8551473) offset(0) size(131072)
2024/01/26 13:01:55.398996 [ERROR] super.go:405: Read: ino(8551473) req(Read [ID=0x114517ec Node=0x22f89 Uid=53801 Gid=53801 Pid=1769104] 0x16 131072 @0x0 dir=false fl=0 lock=0 ffl=OpenReadOnly) err(bad file descriptor) size(0)
```

**Comment by bboyCH4** [comment]
closed #3060
