### ISSUE TITLE
[Bug]: objectnode SIGSEGV crash when s3cmd put file-4M.txt

### ISSUE THREAD

**Issue by jianwei1216** [cubefs/cubefs#3435]
### Contact Details

jianwei1216@qq.com

### Is there an existing issue for this?

- [X] I have searched all the existing issues

### Priority

high

### Environment

```markdown
- CubeFS version: 3.3.2
- Deployment mode(docker or standalone or cluster): docker compile devel (standalone) 
- Dependent components: object + blobstore
- OS kernel version(Ubuntu or CentOS): centos 7.9.2009
- CPU/Memory: x86_64  16G
- Others:
```

### Current Behavior

1. create cfs cluster
```
sh ./shell/depoly.sh ./build/data/disk ens33
```

2. create blobstore cluster
```
cd blobstore
./run.sh --consul
```

3. create user and volume
```
cfs-cli user create testuser -y
cfs-cli volume create test-cold testuser --vol-type 1 --capacity 1000 --mp-count 100
```

4. start objectnode
```
build/bin/cfs-server -f -c ./cmd/cfg/objectnode.json &
```

6. s3cmd put 4M file
```
# ls -l file-4M
-rw-r--r--. 1 root root 4194304 Jul  7 03:36 file-4M

# s3cmd put file-4M s3://test-cold/file-4M.txt
```

8. object SIGSEGV crash
```
2024/07/07 04:17:10 Hello, CubeFS Storage
CubeFS Server
Version : v3.3.2
Branch  : v3.3.2-test
Commit  : 3bed539b361bc02e3eea47cc28d71d91f2b82a59
Build   : go1.22.5 linux amd64 2024-07-07 03:12

2024/07/07 04:17:10 {1048576 1048576}
2024/07/07 04:17:10 Rlimit Final {1024000 1024000}
2024/07/07 04:17:10 action[interceptSignal] register system signal.
2024/07/07 04:17:10 server start success, pid 27596, role objectnode
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xdf2a73]

goroutine 196 [running]:
github.com/cubefs/cubefs/sdk/data/blobstore.(*BlobStoreClient).Write(0x0, {0x1cc62a8, 0x278fa60}, {0xc00705ccc5, 0x9}, {0xc00889e000, 0x400000, 0x400000}, 0x400000)
	sdk/data/blobstore/blobstore_client.go:133 +0x553
github.com/cubefs/cubefs/sdk/data/blobstore.(*Writer).writeSlice(0xc007306000, {0x1cc62a8, 0x278fa60}, 0xc007360000, 0x0)
	sdk/data/blobstore/writer.go:472 +0x1ca
github.com/cubefs/cubefs/sdk/data/blobstore.(*Writer).WriteFromReader.func1.1()
	sdk/data/blobstore/writer.go:241 +0x91
github.com/cubefs/cubefs/sdk/data/blobstore.(*Executor).Run.func1()
	sdk/data/blobstore/task_pool.go:70 +0x29
created by github.com/cubefs/cubefs/sdk/data/blobstore.(*Executor).Run in goroutine 93
	sdk/data/blobstore/task_pool.go:69 +0x96
```

### CubeFS Log

```
2024/07/07 04:17:10 Hello, CubeFS Storage
CubeFS Server
Version : v3.3.2
Branch  : v3.3.2-test
Commit  : 3bed539b361bc02e3eea47cc28d71d91f2b82a59
Build   : go1.22.5 linux amd64 2024-07-07 03:12

2024/07/07 04:17:10 {1048576 1048576}
2024/07/07 04:17:10 Rlimit Final {1024000 1024000}
2024/07/07 04:17:10 action[interceptSignal] register system signal.
2024/07/07 04:17:10 server start success, pid 27596, role objectnode
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xdf2a73]

goroutine 196 [running]:
github.com/cubefs/cubefs/sdk/data/blobstore.(*BlobStoreClient).Write(0x0, {0x1cc62a8, 0x278fa60}, {0xc00705ccc5, 0x9}, {0xc00889e000, 0x400000, 0x400000}, 0x400000)
	sdk/data/blobstore/blobstore_client.go:133 +0x553
github.com/cubefs/cubefs/sdk/data/blobstore.(*Writer).writeSlice(0xc007306000, {0x1cc62a8, 0x278fa60}, 0xc007360000, 0x0)
	sdk/data/blobstore/writer.go:472 +0x1ca
github.com/cubefs/cubefs/sdk/data/blobstore.(*Writer).WriteFromReader.func1.1()
	sdk/data/blobstore/writer.go:241 +0x91
github.com/cubefs/cubefs/sdk/data/blobstore.(*Executor).Run.func1()
	sdk/data/blobstore/task_pool.go:70 +0x29
created by github.com/cubefs/cubefs/sdk/data/blobstore.(*Executor).Run in goroutine 93
	sdk/data/blobstore/task_pool.go:69 +0x96
```

**Comment by jianwei1216** [comment]
```
118 func (ebs *BlobStoreClient) Write(ctx context.Context, volName string, data []byte, size uint32) (location access.Location, err error) {
119         bgTime := stat.BeginStat()
120         defer func() {
121                 stat.EndStat("ebs-write", err, bgTime, 1)
122         }()
123
124         fmt.Printf("zhangjianwei ebs(%v) write, ctx(%v), volName(%v), data(%v), size(%v)", ebs, ctx, volName, data, size) //zhangjianwei
125
126         requestId := uuid.New().String()
127         log.LogDebugf("TRACE Ebs Write Enter,requestId(%v)  len(%v)", requestId, size)
128         start := time.Now()
129         ctx = access.WithRequestID(ctx, requestId)
130         metric := exporter.NewTPCnt(createOPMetric(data, "ebswrite"))
131         defer func() {
132                 metric.SetWithLabels(err, map[string]string{exporter.Vol: volName})
133         }()
134
135         for i := 0; i < MaxRetryTimes; i++ {
136                 location, _, err = ebs.client.Put(ctx, &access.PutArgs{  // crash here, why ebs is nil ? 
137                         Size: int64(size),
138                         Body: bytes.NewReader(data),
139                 })
140                 if err == nil {
141                         break
142                 }
143                 log.LogWarnf("TRACE Ebs write, err(%v), requestId(%v),retryTimes(%v)", err, requestId, i)
144                 time.Sleep(RetrySleepInterval)
145         }
146         if err != nil {
147                 log.LogErrorf("TRACE Ebs write,err(%v),requestId(%v)", err.Error(), requestId)
148                 return location, err
149         }
150         elapsed := time.Since(start)
151         log.LogDebugf("TRACE Ebs Write Exit,requestId(%v)  len(%v) consume(%v)ns", requestId, len(data), elapsed.Nanoseconds())
152         return location, nil
153 }
```

```
zhangjianwei2 ebs(<nil>) write, ctx(context.Background), volName(test-cold), data([0 0 0 0 0]), size(4194304)
```

**Comment by jianwei1216** [comment]
```
# cat cmd/cfg/objectnode.json
{
  "role": "objectnode",
  "hosts": "127.0.0.1",
  "logDir": "./build/run/logs/",
  "logLevel": "debug",
  "listen": "80",
  "consul_agent_addr": "127.0.0.1:8500",
  "priority_addrs": [
      "127.0.0.1:9500"
  ],
  "masterAddr": [
    "172.16.1.101:17010",
    "172.16.1.102:17010",
    "172.16.1.103:17010"
  ],
  "enableHTTPS": "false",
  "certFile": ""
}
```


```
# cat ./build/data/disk/conf/master1.conf
{
  "clusterName": "cfs_dev",
  "id": "1",
  "role": "master",
  "ip": "172.16.1.101",
  "bindIp": "true",
  "listen": "17010",
  "peers": "1:172.16.1.101:17010,2:172.16.1.102:17010,3:172.16.1.103:17010",
  "ebsAddr": "http://127.0.0.1:8500",  // this ip is Consul IP , not is clustermgr IP for blobstore
  "consulAddr": "http://127.0.0.1:8500",
  "retainLogs": "2000",
  "logLevel": "debug",
  "logDir": "./build/data/disk/master1/logs",
  "warnLogDir": "./build/data/disk/master1/logs",
  "walDir": "./build/data/disk/master1/wal",
  "storeDir": "./build/data/disk/master1/store",
  "metaNodeReservedMem": "536870912"
}
```

**Comment by jianwei1216** [comment]
Objectnode only needs to interact with the master and access components.

objectnode <==> master // Get ebsAddr (blobstore consul IP)

objectnode <==> ebsAddr(consul IP) <==> access // Upload and download objects

access <==> clustermgr(blobstore) / blobnode interaction
